apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-hello-linux-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: helloalias = 588184019567.dkr.ecr.ap-southeast-1.amazonaws.com/hello/helloservice
    argocd-image-updater.argoproj.io/helloalias.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/helloalias.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/txnt3ch/argocd-apps.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://1589A63B8955A6C6607187244561A0FE.gr7.ap-southeast-1.eks.amazonaws.com
    namespace: eks-hello-app


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true