apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-hello-linux-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: eks-hello-linux-app
  template:
    metadata:
      labels:
        app: eks-hello-linux-app
    spec:
      containers:
        - image: 588184019567.dkr.ecr.ap-southeast-1.amazonaws.com/hello/helloservice:af2d73d0eb3e5ca8bed24e0fd9fe8069c74409af
          name: eks-hello-linux-app
          ports:
            - containerPort: 80